site_name: Solutions to Selected Exercises from Elements of Abstract Algebra
markdown_extensions:
  - mdx_math
  - attr_list
  - footnotes
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-AMS-MML_HTMLorMML
extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.css  
theme:
  name: readthedocs  # Use the Material theme
nav:
  - Home: index.md
  - Set Theory:
      - Set Theory Remarks.md
  - Group Theory:
      - Group Theory Remarks.md
      - The Definition of Group Structure:
          - 26a.md
          - 26b.md
          - 26c.md
          - 26d.md
          - 28b.md
          - 28c.md
      - Examples of group structure:
          - a
      - Subgroups and cosets: 
          - 35a.md
  - Field Theory:
      - f
  - Galois Theory:
      - g
  - Ring Theory:
      - r
